#!/usr/bin/env bash
# Dispplay the buzz to multiple of 5 and fizz for multiple of 3

 for i in {1..100}; do
   if (( i % 15 == 0 )); then
     echo "FizzBuzz"
   elif (( i % 5 == 0 )); then
     echo "Buzz"
   elif (( i % 3 == 0 )); then
     echo "Fizz"
   else 
     echo "$i"
   fi
 done
