#!/usr/bin/env bash
# use IFS in /etc/passwd using while loop.

while IFS=: read -r username passwd userid groupid userinfo homedir shell; do
echo " The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $passwd, more info about the user here: $userinfo"
done < /etc/passwd
