#!/usr/bin/env bash
# use IFS in /etc/passwd using while loop
# Read /etc/passwd line by line
while IFS=: read -r username password userid groupid userinfo homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd
