#!/usr/bin/env bash
#display best school 10 times but on 9th iteration display hello.
 i=1
 while [ $i -le 10 ]; do
   if [ $i -eq 9 ]; then
     echo "Hi"
   else 
     echo "Best School"
   fi
  ((i++))
 done
