#!/usr/bin/env bash
# Use while loop but the 4 th iteration diaplay bad luck and 8 th iteration displays bad luck.
 i=1
  while [ $i -le 10 ]; do
    if [ $i -eq 4 ] ; then
       echo "bad luck"
    elif [ $i -eq 8 ]; then
       echo "good luck"
    else
       echo "Best Schoool"
    fi
    ((i++))
  done 
