#!/usr/bin/env bash
# Check if school file exists or not existf the file exists: school file exists,if the file does not exist: school file does not exist,If the file exists, print:,if the file is empty: school file is empty,if the file is not empty: school file is not empty and if the file is a regular file: school is a regular file,if the file is not a regular file: (nothi

file="school.txt"

if [ -e "$file" ]; then
  if [ -f "$file" ]; then
    echo "school is a regular file"
    if [ -s "$file" ]; then
      echo "school file is not empty"
    else
      echo "school file is empty"
    fi

    echo "school file exists"
  fi
else
  echo "school file does not exist"
fi
